name: clash.meta
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              type: "WithoutCGO",
              target: "linux-amd64 linux-amd64-compatible",
              id: "1",
            }
          - { type: "WithoutCGO", target: "linux-arm64", id: "2" }
          - {
              type: "WithoutCGO",
              target: "windows-amd64-compatible windows-amd64",
              id: "3",
            }

    steps:
      - name: Clone code
        run: |
          rm -rf ../clash
          git clone -b Alpha https://github.com/MetaCubeX/Clash.Meta.git ../clash
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build WithoutCGO
        if: ${{ matrix.job.type=='WithoutCGO' }}
        env:
          NAME: Clash.Meta
          BINDIR: bin
        run: |
          cd ../clash
          sed -i "s@-tags with_gvisor@-tags with_gvisor,no_fake_tcp@g" Makefile
          make -j$(($(nproc) + 1)) ${{ matrix.job.target }}
      - name: Move
        if: ${{  success() }}
        run: |
          mkdir -p bin/
          mv ../clash/bin/clash.meta* bin/
      - uses: actions/upload-artifact@v3
        if: ${{  success() }}
        with:
          name: artifact
          path: bin/
  Upload-Release:
    permissions: write-all
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag_name: clash.meta
          files: bin/*

  Docker:
    permissions: write-all
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Clone code
        run: |
          rm -rf ../clash
          git clone -b Alpha https://github.com/MetaCubeX/Clash.Meta.git ../clash
      - name: Copy script
        run: |
          ls
          cp file-name.sh ../clash/docker/file-name.sh
          cp Dockerfile ../clash/Dockerfile
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ../clash/bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ../clash/bin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/skyxim/clash.meta

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ../clash
          push: true
          # https://github.com/docker/build-push-action/issues/820
          provenance: false
          tags: ghcr.io/skyxim/clash.meta:latest
