name: sing-box
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
env:
  QEMU_STRACE: 1
jobs:
  Build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-arm64
            goos: linux
            goarch: arm64
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      CGO_ENABLED: 0
      TAGS: with_quic,with_wireguard,with_grpc,with_gvisor
    steps:
      - name: Clone code
        run: |
          rm -rf ../sing-box
          git clone -b dev https://github.com/SagerNet/sing-box.git ../sing-box
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        id: build
        run: cd ../sing-box && make
      - name: Move
        if: ${{  success() }}
        run: |
          mkdir -p ./bin
          mv ../sing-box/sing-box* "./bin/sing-box-$GOOS-$GOARCH"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: bin/
  Upload-Release:
    permissions: write-all
    needs: [Build]
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag_name: sing-box
          files: bin/*

  Docker:
    needs: [Build]
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:master
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zalixio/sing-box
      - name: Build and release Docker images
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: ghcr.io/zalixio/sing-box:latest
          context: .
          file: sing-box-Dockerfile
          push: true
