name: sing-box
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
env:
  QEMU_STRACE: 1
jobs:
  Docker:
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Clone code
        run: |
          rm -rf ../sing-box
          git clone -b dev https://github.com/SagerNet/sing-box.git ../sing-box
          cd ../sing-box
          sed -i "s@apk add git build-base@apk update \&\& apk add git build-base@g" Dockerfile
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zalixio/sing-box
      - name: Build and release Docker images
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          target: dist
          provenance: false
          tags: ghcr.io/zalixio/sing-box:latest
          context: ../sing-box
          push: true
